services:
  database:
    image: mysql:8.0
    container_name: warehouse_db_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret_password
      MYSQL_DATABASE: warehouse_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: